# Use root/example as user/password credentials
version: '3.1'

services:
  postgres:
    image: postgres
    ports:
      - 5445:5432
    environment:
      POSTGRES_DATABASE: postgres
      POSTGRES_USER: postgres
      POSTGRES_ROOT_PASSWORD: 12345
      POSTGRES_PASSWORD: 12345
    volumes:
      - './docker/data/postgresql:/var/lib/postgresql/data'
  redis:
    image: redis
    ports:
      - 6381:6379

